apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-box
  title: Create Box instance
  description: Will create a new gcp Box instance for ...
  tags:
    - gcp
    - box
    - infrastructure
spec:
  owner: irados
  type: box
  parameters:
    - title: "Provide information"
      required:
        - owner
        - name
      properties:
        owner:
          title: "Owner"
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        description:
          title: Description
          type: string
          description: A description for the component
        name:
          title: "name"
          type: string
          description: Unique name 
        repo:
          title: "repo"
          type: string
          description: Unique name 
        token:
          type: string
          title: "token"
  steps:
    - id: fetchRepo
      name: Fetch Repo
      action: fetch:plain
      input:
        # url: https://irados:${{ parameters.token }}@github.com/irados/backstagetest.git
        url: https://github.com/irados/backstagetest.git
    - id: fetch
      name: Template Skeleton files
      action: fetch:template
      input:
        url: ./skeleton
        # targetPath: ./tmp
        values:
          name: ${{ parameters.name }}
          repo: ${{ parameters.repo }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: 'github.com/?repo=backstagetest&project=irados&owner=irados'
        title: Creating catalog-info.yaml ${{ parameters.name }} for backstage
        branchName: 'testbranch'
        sourceBranch: 'testbranch'
        token: ${{ parameters.token }}
        description: |
          # New project: ${{ parameters.name }}
          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else '.' }}
        commitAction: create
        removeSourceBranch: true
    # - id: publish
    #   name: Publish
    #   action: publish:bitbucketServer:pull-request
    #   input:
    #     fromRef: {
    #       "id":"refs/heads/feature",
    #       "repository":{
    #         "slug":"testbranch",
    #         "name":None,
    #         "project":{
    #             "key":"~irados"
    #             }
    #         }
    #     }
    #     toRef: {
    #       "id":"refs/heads/master",
    #       "repository":{
    #         "slug":"master",
    #         "name":None,
    #         "project":{
    #             "key":"~irados"
    #             }
    #         }
    #     }
    #       # id: "ref/heads/testbranch"
    #       # displayId: 'testbranch',
    #       # type: 'BRANCH' }
    #     # repoUrl: scm.test.xxx.se?repo=${{ parameters.repoName }}&project=${{ parameters.projectName }}
    #     # sourceBranch: ${{ parameters.prBranch }}
    #     # targetBranch: ${{ parameters.targetBranch }}
    #     sourceBranch: 'some testbranch'
    #     targetBranch: 'master'
    #     title: Merge new box into projects repo
    #     description: This PR was created by a Backstage scaffolder task to add CI-pipeline to the project.
    #     token: ${{ parameters.token }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      # - url: ${{steps.publish.output.remoteUrl}}
      - token: ${{ GITHUB_TOKEN }}
        text: "Pull request"