apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: Gcp system
  name: gcp-system
  description: complette gcp platform.
spec:
  owner: group:gcp-ug-something
  domain: sample-domain
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: irados
spec:
  profile:
    displayName: Ivan Rados
    email: ivan.rados@bla.com
  memberOf: [Somegroup]
---
# apiVersion: backstage.io/v1alpha1
# kind: Group  
# metadata:
#   name: Somegroup
#   description: Some Team
# spec:
#   type: team
#   profile:
#     displayName: Admins
#     email: Somegroup@somedomain.net
#     # picture: https://avatars.dicebear.com/api/identicon/backstage-admin.svg
#   children: []
#   members:
#     - user:default/irados
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: a-team-box
  title: Box für some-Team # optional, human readable component name
  description: Box docu test catalog.
  tags:
    - box
    - test
  annotations:
    github.com/project-slug: <github-org>/<github-repo>
spec:
  type: box
  owner: user:irados
  system: gcp-system
  lifecycle: experimental